### ISSUE TITLE
Setup SSR - server rendering

### ISSUE THREAD

**Issue by FunixG** [PacifistaMC/PacifistaWebsite#1]
usefull for SEO ranking

**Comment by FunixG** [comment]
![image](https://user-images.githubusercontent.com/44138938/223995805-4a278813-428a-46bd-a6d4-c1b0e0e3adde.png)

**Comment by lbrun25** [comment]
SSG and SSR are both great for SEO. This is because both of them generate their HTML outputs on the server at either build or request time. This means both can be crawled and indexed by search engine bots.

Both rendering methods also render pages quickly, which will help SEO rankings. However, out of the two, SSG does render faster so if you have particularly large pages and can use it, SSG will help more.

Ultimately, the best approach for SEO depends on the specific needs and goals of the website. For websites with primarily static content, SSG may be a better fit. For websites with more dynamic content, SSR may be more appropriate.

ISR can be advantageous because it provides the benefits of SSG (fast load times, easy crawlability by search engines, and better control over on-page SEO elements) while also ensuring that content is always up-to-date, like with SSR. This can lead to better search engine rankings and a better user experience.

**Comment by FunixG** [comment]
> SSG and SSR are both great for SEO. This is because both of them generate their HTML outputs on the server at either build or request time. This means both can be crawled and indexed by search engine bots.
> 
> Both rendering methods also render pages quickly, which will help SEO rankings. However, out of the two, SSG does render faster so if you have particularly large pages and can use it, SSG will help more.
> 
> Ultimately, the best approach for SEO depends on the specific needs and goals of the website. For websites with primarily static content, SSG may be a better fit. For websites with more dynamic content, SSR may be more appropriate.
> 
> ISR can be advantageous because it provides the benefits of SSG (fast load times, easy crawlability by search engines, and better control over on-page SEO elements) while also ensuring that content is always up-to-date, like with SSR. This can lead to better search engine rankings and a better user experience.

Hey @lbrun25 ! Thanks for the feedback and great advices !
Actually the website will have a shop and many dynamic content so if I understand well, I might use SSR for final rendering.

Thanks for the surprise aha :D
